-- 1.查询某机构的部门、职位、用户信息 --
SELECT U.USERNAME,D.ID AS DEPART_ID , D.NAME AS DEPART_NAME, p.ID AS POSITION_ID, P.`name` AS POSITION_NAME, O.ID AS OFFICE_ID, O.`NAME` AS OFFICE_NAME FROM SYSTEM_USER AS U
INNER JOIN SYSTEM_POSTION AS P ON P.ID = U.SYSTEM_POSITION_ID
INNER JOIN SYSTEM_DEPART AS D ON D.ID = P.SYSTEM_DEPART_ID
INNER JOIN SYSTEM_OFFICE AS O ON O.ID = D.SYSTEM_OFFICE_ID
WHERE O.ID = 1


-- 2.查询某机构的部门 --
SELECT D.* FROM SYSTEM_DEPART AS D
WHERE D.SYSTEM_OFFICE_ID IN(SELECT ID FROM SYSTEM_OFFICE WHERE ID = 1);

-- 3.查询某部门的职位 -- 
SELECT P.* FROM SYSTEM_POSTION AS P
WHERE P.SYSTEM_DEPART_ID IN(SELECT ID FROM SYSTEM_DEPART WHERE ID = 1);


-- 3.查询某机构的职位 --
SELECT P.* FROM SYSTEM_POSTION AS P
INNER JOIN SYSTEM_DEPART AS D ON D.ID = P.SYSTEM_DEPART_ID
WHERE D.SYSTEM_OFFICE_ID IN(SELECT ID FROM SYSTEM_OFFICE WHERE ID = 1);



-- 查询职位子节点函数 --
DROP FUNCTION IF EXISTS FN_POSITION_CHILD_LIST;

CREATE FUNCTION FN_POSITION_CHILD_LIST(ROOT_ID INT) RETURNS VARCHAR(1000) #ROOT_ID为你要查询的节点
BEGIN

#声明两个临时变量
DECLARE TEMP VARCHAR(1000);
DECLARE TEMP_CHILD VARCHAR(1000);
SET TEMP = '$';
SET TEMP_CHILD=CAST(ROOT_ID AS CHAR);#把ROOTID强制转换为字符


WHILE TEMP_CHILD IS NOT NULL DO
SET TEMP = CONCAT(TEMP,',',TEMP_CHILD);#循环把所有节点连接成字符串。
SELECT GROUP_CONCAT(ID) INTO TEMP_CHILD FROM SYSTEM_POSTION WHERE FIND_IN_SET(PARENT_ID,TEMP_CHILD)>0 ;
END WHILE;
RETURN TEMP;

END


SELECT FN_POSITION_CHILD_LIST(1);

SELECT * FROM SYSTEM_POSTION AS T1 WHERE FIND_IN_SET(T1.ID, FN_POSITION_CHILD_LIST(1)) AND T1.SYSTEM_DEPART_ID = 1; 
